### ISSUE TITLE
redux store?

### ISSUE THREAD

**Issue by gardner** [Gethyl/GraphQLPagination#2]
Hello and thank you for publishing this code! It's been very useful learning about apollo and infinite scroll. I was just wondering if you connect the redux store does anything in this example or is it just good practice for when you plan to grow the codebase into a large app? Do you use the redux dev tools to monitor the actions? Thanks again!

**Comment by Gethyl** [comment]
Hi,

Glad you liked it :) . In this example Redux store is actually not required and you could remove it.I think initially I wanted to create a much more complex example and then stripped out those complexities. And the Redux store here is left over of my initial idea. But when you build an actually web/mobile app, it will not be just one component as I have shown in this example, but there will be a number of components. 

You could control state of each component by using `this.setState` and re-render that component but when you have multiple components and want to control the states not on individual component but on a set of components or on the entire app level, then I would recommend the simplest and easiest way is to use *Redux*.

I do use Redux dev tool to monitor actions at times while debugging. 

Another useful devTool I have found is [Apollo Dev Tools](https://github.com/apollographql/apollo-client-devtools).

**Comment by gardner** [comment]
Thanks for the explanation @Gethyl. I was wondering if there was some sort of magic happening there. I just added Apollo Dev Tools to my browser!
